import {  PlcTagBase,
 PlcMemoryType,
 BoolPlcTag,
 BytePlcTag,
 CharPlcTag,
 USIntPlcTag,
 HwAnyPlcTag,
 HwioPlcTag,
 Int16PlcTag,
 UInt16PlcTag,
 WordlcTag,
 DWordPlcTag,
 DIntPlcTag,
 UDIntPlcTag,
 RealPlcTag,
 LRealPlcTag,
 TimeMsPlcTag,
 DatePLcTag,
 Date_And_TimePlcTag,
 DtlPlcTag,
 StringPlcTag,
} from '../../Types/BaseTypes';
import { Conveyor_UDT } from '../../Types/Conveyors/Conveyor_UDT';
export class CONV_DB_DB49 {

	KeyName : string;
	Name: string;
	Number: number;
	Id: number;
	public static Design = 'CONV_DB_DB49'
	_empty: Conveyor_UDT;
	_CONV_101: Conveyor_UDT;
	_CONV_102L: Conveyor_UDT;
	_CONV_102R: Conveyor_UDT;
	_CONV_103L: Conveyor_UDT;
	_CONV_103R: Conveyor_UDT;
	_CONV_104L: Conveyor_UDT;
	_CONV_104R: Conveyor_UDT;
	_CONV_105L: Conveyor_UDT;
	_CONV_105R: Conveyor_UDT;
	_CONV_106R: Conveyor_UDT;
	_CONV_107R: Conveyor_UDT;
	_CONV_108L: Conveyor_UDT;
	_CONV_108R: Conveyor_UDT;
	_CONV_109L: Conveyor_UDT;
	_CONV_109R: Conveyor_UDT;
	_CONV_110L: Conveyor_UDT;
	_CONV_110R: Conveyor_UDT;
	_CONV_111L: Conveyor_UDT;
	_CONV_111R: Conveyor_UDT;
	_CONV_112R: Conveyor_UDT;
	_CONV_113L: Conveyor_UDT;
	_CONV_113R: Conveyor_UDT;
	_CONV_114L: Conveyor_UDT;
	_CONV_114R: Conveyor_UDT;
	_CONV_115L: Conveyor_UDT;
	_CONV_115R: Conveyor_UDT;
	_CONV_201R_BELTS: Conveyor_UDT;
	_CONV_203R_BELTS: Conveyor_UDT;
	_CONV_301R: Conveyor_UDT;
	_CONV_302L: Conveyor_UDT;
	_CONV_302R: Conveyor_UDT;
	_CONV_303L: Conveyor_UDT;
	_CONV_303R: Conveyor_UDT;
	_CONV_304L: Conveyor_UDT;
	_CONV_304R: Conveyor_UDT;
	_CONV_305R: Conveyor_UDT;

	Constructor(){
	this.KeyName = "CONV_DB_DB49"	}
}